# Generated by Django 3.0.4 on 2020-06-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_auto_20200618_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfercar',
            old_name='product',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='transfercar',
            old_name='quantity',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='transfercar',
            old_name='amount',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='take_off',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='transfercar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transfercar',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transfercar',
            name='transfer',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.TransferCar'),
        ),
        migrations.AddField(
            model_name='transfercar',
            name='arrive',
            field=models.CharField(blank=True, choices=[('Havalimani', 'Havalimani'), ('Havalimani-*', 'Havalimani-*'), ('Ankara', 'Ankara'), ('-', '-'), ('Istanbul', 'Istanbul'), ('Bursa', 'Bursa'), ('Izmir', 'Izmir')], default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='transfercar',
            name='take_off',
            field=models.CharField(blank=True, choices=[('Havalimani', 'Havalimani'), ('Havalimani-*', 'Havalimani-*'), ('Ankara', 'Ankara'), ('-', '-'), ('Istanbul', 'Istanbul'), ('Bursa', 'Bursa'), ('Izmir', 'Izmir')], default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='transfercar',
            name='transfer_date',
            field=models.DateField(blank=True, default='2020-11-11'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfercar',
            name='status',
            field=models.CharField(choices=[('New', 'New')], default='New', max_length=20),
        ),
        migrations.DeleteModel(
            name='TransferCart',
        ),
    ]
