# Generated by Django 3.0.4 on 2020-06-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_auto_20200620_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercar',
            name='transfer_time',
            field=models.TimeField(null=True),
        ),
    ]
